version: '2'
networks:
  proxy-tier:
    external:
      name: nginx-proxy
volumes:
  # TODO: server-conf and server-strage need not be 2 separate volumes
  server-conf:
  server-storage:
  # - /home/.tradle
services:
# START adapted from: https://github.com/fatk/docker-letsencrypt-nginx-proxy-companion-examples/blob/master/docker-compose/v2/simple-site/docker-compose.yml
  nginx:
    image: nginx
    container_name: nginx
    ports:
      - "80"
      - "443"
    volumes:
      - "/etc/nginx/conf.d"
      - "/etc/nginx/vhost.d"
      - "/usr/share/nginx/html"
      - "${SSL_CERTS_DIR}:/etc/nginx/certs:ro"
    networks:
      - proxy-tier
  nginx-gen:
    image: jwilder/docker-gen
    container_name: nginx-gen
    volumes:
      - "/var/run/docker.sock:/tmp/docker.sock:ro"
      - "./nginx-compose-v2.tmpl:/etc/docker-gen/templates/nginx.tmpl:ro"
    volumes_from:
      - nginx
    entrypoint: /usr/local/bin/docker-gen -notify-sighup nginx -watch -only-exposed -wait 5s:30s /etc/docker-gen/templates/nginx.tmpl /etc/nginx/conf.d/default.conf
  letsencrypt-nginx-proxy-companion:
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: letsencrypt-nginx-proxy-companion
    volumes_from:
      - nginx
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "${SSL_CERTS_DIR}:/etc/nginx/certs:rw"
    environment:
      - NGINX_DOCKER_GEN_CONTAINER=nginx-gen
# END adapted from: https://github.com/fatk/docker-letsencrypt-nginx-proxy-companion-examples/blob/master/docker-compose/v2/simple-site/docker-compose.yml
  tradle:
    image: tradle/server-cli:v2
    container_name: tradle-server
    restart: always
    environment:
      - VIRTUAL_HOST=${TRADLE_SERVER_URL}
      - VIRTUAL_PORT=80
      - VIRTUAL_NETWORK=nginx-proxy
      - LETSENCRYPT_HOST=${TRADLE_SERVER_URL}
      - LETSENCRYPT_EMAIL=mark@tradle.io
      - NODE_ENV=development
      - AUTORUN=1
      - DEBUG=*
      - HOME=/home
      - CONF_PATH=./conf
      - STORAGE_PATH=./storage
      - TRADLE_SERVER_PORT=80
    volumes:
      - server-conf:/opt/app/conf
      - server-storage:/opt/app/storage
    expose:
      - "80"
    tty: true
    stdin_open: true
    networks:
      - proxy-tier
