server-cli:
  image: tradle/server-cli:v2.3
  restart: always
  environment:
    NODE_ENV: development
#    NODE_ENV: production
    AUTORUN: "1"
    DEBUG: "*"
    HOME: "/home"
    CONF_PATH: "./conf"
    STORAGE_PATH: "./storage"
    TRADLE_SERVER_PORT: 44446
    SSL_CERTIFICATE_PATH: "/etc/letsencrypt/live/${TRADLE_HOST}"
  ports:
    - "44445:44445"
  volumes_from:
    - data
  tty: true
  stdin_open: true
  net: host
data:
  image: cogniteev/echo
  command: echo 'data container for Tradle'
  volumes:
    - /opt/app/conf
    - /opt/app/storage
    - /home/.tradle
    - "/etc/letsencrypt/live/${TRADLE_HOST}:/etc/letsencrypt/live/${TRADLE_HOST}"
