version: '2'
volumes:
  server-conf:
    external: true
  server-storage:
    external: true
services:
  nginx:
    image: nginx
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "/etc/nginx/conf.d"
      - "/etc/nginx/vhost.d"
      - "/usr/share/nginx/html"
      - "/var/proxy/certs:/etc/nginx/certs:ro"
  nginx-gen:
    image: jwilder/docker-gen
    container_name: nginx-gen
    volumes_from:
      - nginx
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./:/etc/docker-gen/templates
    entrypoint: /usr/local/bin/docker-gen -notify-sighup nginx -watch /etc/docker-gen/templates/nginx.tmpl /etc/nginx/conf.d/default.conf
  tradle:
    image: tradle/server-cli:v2.3
    container_name: tradle-server
    restart: always
    environment:
      - VIRTUAL_HOST=${TRADLE_SERVER_URL}
      - VIRTUAL_PORT=80
      - NODE_ENV=development
      - AUTORUN=1
      - DEBUG=tradle:*
      - HOME=/home
      - CONF_PATH=./conf
      - STORAGE_PATH=./storage
      - TRADLE_SERVER_PORT=80
    volumes:
      - server-conf:/opt/app/conf
      - server-storage:/opt/app/storage
    ports:
      - "80"
    tty: true
    stdin_open: true
