#!/bin/bash
# This example will run a basic nginx server provisionned with an index.html file

# This nginx container will get a configuration generated by the docker-gen instance and act as a reverse-proxy
echo "Starting nginx instance..."
source .env
docker run -d -p 80:80 -p 443:443 \
    --name nginx \
    -v /etc/nginx/conf.d  \
    -v /etc/nginx/vhost.d \
    -v /usr/share/nginx/html \
    -v /var/proxy/certs:/etc/nginx/certs:ro \
    nginx

# This nginx-gen container using the docker-gen image will generate a 'default.conf' file from the 'nginx.tmpl' located in volumes/proxy/templates.
echo "Starting docker-gen instance..."
docker run -d \
    --name nginx-gen \
    --volumes-from nginx \
    -v $(pwd)/nginx.tmpl:/etc/docker-gen/templates/nginx.tmpl:ro \
    -v /var/run/docker.sock:/tmp/docker.sock:ro \
    jwilder/docker-gen \
    -notify-sighup nginx -watch -only-exposed -wait 5s:30s /etc/docker-gen/templates/nginx.tmpl /etc/nginx/conf.d/default.conf


#echo "Starting letsencrypt-nginx-proxy-companion..."
#docker run -d \
#    --name letsencrypt \
#    -e "NGINX_DOCKER_GEN_CONTAINER=nginx-gen" \
#    --volumes-from nginx \
#    -v /var/proxy/certs:/etc/nginx/certs:rw \
#    -v /var/run/docker.sock:/var/run/docker.sock:ro \
#    jrcs/letsencrypt-nginx-proxy-companion

echo "Starting tradle server"
docker run -id \
    --name tradle-server \
    -e "VIRTUAL_HOST=${TRADLE_SERVER_URL}" \
    -e VIRTUAL_PORT=80 \
    -e TRADLE_SERVER_PORT=80 \
    -e "LETSENCRYPT_HOST=${TRADLE_SERVER_URL}" \
    -e LETSENCRYPT_EMAIL=${DEV_EMAIL} \
    -e NODE_ENV=development \
    -e AUTORUN=1 \
    -e DEBUG=* \
    -e HOME=/home \
    -e CONF_PATH=./conf \
    -e STORAGE_PATH=./storage \
    -v $(pwd)/tradle-server-conf.d/:/etc/nginx/conf.d \
    -v tradle_data_2:/opt/app/storage \
    -v tradle_conf_2:/opt/app/conf \
    --expose 80 \
    tradle/server-cli:v2
