version: '2'
#networks:
#  front:
#  back:
volumes:
  pushdb:
services:
  nginx:
    image: nginx
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /tmp/nginx:/etc/nginx/conf.d
# TODO: add SSL certs
      - ./:/etc/nginx/certs/
#    networks:
#      - front
  nginx-gen:
    image: jwilder/docker-gen
    container_name: nginx-gen
    volumes_from:
      - nginx
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./:/etc/docker-gen/templates
#    networks:
#      - front
    entrypoint: /usr/local/bin/docker-gen -notify-sighup nginx -watch /etc/docker-gen/templates/nginx.tmpl /etc/nginx/conf.d/default.conf
  redis:
    image: redis
    ports:
      - 6379
#    networks:
#      - back
    environment:
      - VIRTUAL_HOST=redis
      - VIRTUAL_PORT=6379
  pushd:
    image: amsdard/pushd:latest
    volumes:
      - ./settings:/opt/settings
    ports:
      - 8081
    environment:
      - REDIS_PORT=6379
      - REDIS_HOST=redis
      # - REDIS_PASSWORD="..."
      - GCM_KEY=${GCM_KEY}
      - APNS_CERT=/opt/settings/apns-cert.pem
      - APNS_KEY=/opt/settings/apns-key.pem
      - PUSHD_LOGGING_LEVEL=silly
      - VIRTUAL_HOST=pushd
      - VIRTUAL_PORT=8081
#    networks:
#      - back
  tradle-push:
    image: tradle/push-server
#    networks:
#      - front
#      - back
    ports:
      - 80
    volumes:
      - pushdb:/opt/app/storage
    environment:
      - VIRTUAL_HOST=push1.tradle.io
    entrypoint: node /opt/app/run.js --db /opt/app/storage/push1.db --pushd http://pushd:8081 --port 80
