version: '2'
networks:
  front:
  back:
volumes:
  pushdb:

services:
  redis:
    image: redis
    ports:
      - 6379
    networks:
      - back
  pushd:
    image: amsdard/pushd:latest
    volumes:
      - ./settings:/opt/settings
    ports:
      - 8081
    environment:
      - REDIS_PORT=6379
      - REDIS_HOST=redis
      # - REDIS_PASSWORD="..."
      - GCM_KEY=${GCM_KEY}
      - APNS_CERT=/opt/settings/apns-cert.pem
      - APNS_KEY=/opt/settings/apns-key.pem
      - PUSHD_LOGGING_LEVEL=silly
    networks:
      - back
  tradle-push:
    image: tradle/push-server
    ports:
      - "80:80"
    networks:
      - front
      - back
    volumes:
      - pushdb:/opt/app/storage
#    environment:
#     - DEBUG=*
    entrypoint: node /opt/app/run.js --db /opt/app/storage/push.db --pushd http://pushd:8081 --port 80
